-- Audit table creation

CREATE TABLE AuditLog (
    LogID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    TransactionID NUMBER,
    ActionType VARCHAR2(20),
    AccountID NUMBER,
    Amount NUMBER,
    LogTimestamp DATE DEFAULT SYSDATE
);


-- trigger creation

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog (
        TransactionID,
        ActionType,
        AccountID,
        Amount
    )
    VALUES (
        :NEW.TransactionID,
        'INSERT',
        :NEW.AccountID,
        :NEW.Amount
    );
END;
/

-- table before the deposit
SELECT * FROM AuditLog WHERE TransactionID = 12;

-- Insert a transaction
INSERT INTO Transactions (TransactionID, AccountID, TransactionDate, Amount, TransactionType)
VALUES (12, 4, SYSDATE, 750, 'Deposit');


-- table after the deposit
SELECT * FROM AuditLog WHERE TransactionID = 12;

